### ISSUE TITLE
research MongoDB search function

### ISSUE THREAD

**Issue by ryanhu021** [hack4impact-calpoly/the-land-conservancy#129]
Do some research on how to perform a search with multiple fields in Mongoose and MongoDB. For example, given a String (e.g. "San Luis Obispo"), we want to be able to search through the date and location fields of Event object in the database. Write your documentation as a reply to this issue.

**Comment by j-ylau** [comment]
If we're given an event object, then we can search through the database using Event.find(props) 

`Event.find({ $and: [ { location: "San Luis Obispo" }, { date: date } ] });`
... using and
`Event.find({ $or: [ { location: "San Luis Obispo" }, { date: date } ] });`
... using or 

I think you can also do the following if I am not forgetting... 

`Event.find({ location: "San Luis Obispo" }).and([{ date: date }])`

I guess you can also use regex, but it should be pretty similar in terms of operations.

**Comment by KimLinhVu** [comment]
To search if multiple fields match the input in Mongoose, you can use an or statement:

`Event.find({ $or: [{ location: "San Luis Obispo" }, { date: "San Luis Obispo" }] })`

This would return all the documents that have location == "San Luis Obispo" or date == "San Luis Obispo" (or both).

---

To search with multiple fields in Mongoose, you can do:

`Event.find({ location: "San Luis Obispo", date: date })`

This would return all the documents in the Event collection that have location == "San Luis Obispo" and date == date.
