### ISSUE TITLE
add back button to edit event page

### ISSUE THREAD

**Issue by ryanchansf** [hack4impact-calpoly/the-land-conservancy#157]
The Edit Event page should have a back arrow button that returns to the Events page. This should be similar to the back arrow seen on the Log Hours page when returning to the Volunteer Log. 

![Image](https://user-images.githubusercontent.com/91078767/217170416-adc41358-2390-4ec5-a14c-5ccb4694cbcc.png)

**Comment by oli-lane** [comment]
pages accessed from navbar will have navbar. Other pages (editevent, loghours, editprize, etc) will have navbar and the back button.
