### ISSUE TITLE
add drag-and-drop feature for pictures on the Edit Prize page

### ISSUE THREAD

**Issue by ryanhu021** [hack4impact-calpoly/the-land-conservancy#169]
The edit prize page should contain a box that allows the user to drag and drop an image of the prize. Look at libraries that can provide the drag-and-drop box and implement it on the frontend, no need to connect anything to the backend for now.

**Comment by oli-lane** [comment]
The variable with the file needs to be added on line 35, I took it out so there wouldn't be a "value never used" error.
