### ISSUE TITLE
Explore a progress bar component

### ISSUE THREAD

**Issue by marissadarnell** [hack4impact-calpoly/the-land-conservancy#48]
### Description
Just do some light internet browsing for a progress bar component for our app. So far, we want it to look similar to the Starbucks progress bar for rewards
 - line with dots/circles as the milestones
 - number labels for each milestone
![image](https://user-images.githubusercontent.com/63181280/156071344-4d9cafdd-bb48-4109-943e-692c913d73a1.png)  
![image](https://user-images.githubusercontent.com/63181280/156083296-3351eb04-2e8d-4768-9e35-0ab9b954c83f.png)

### Checklist

- [x] search for a package
- [x] see if we could do it with a combination of simpler components
- [x] maybe an mui component
- [x]  . . . wherever else you think may be a good resource to find something we could use

##
You can organize your findings together in some sort of document or just message it to me on Slack. Then we can converse about it a bit, either in person, zoom, or just messaging, however you prefer.

**Comment by Ritvik1121** [comment]
I found some possible progress bar implementations that might work. I sent them on slack so let me know what you think of them.

**Comment by marissadarnell** [comment]
resolved
